export const COURSE_DATA_FETCHED_ALL= "COURSE_DATA_FETCHED_ALL"
export const COURSE_BATCH_FETCHED_ALL= "COURSE_BATCH_FETCHED_ALL"
export const ALL_COURSE_DATA = "ALL_COURSE_DATA"
export const MODAL = "MODAL"
